name: journal_app
description: "With clean architecture"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  bloc: ^8.1.4
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.7.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.6
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  lottie: ^3.2.0
  smooth_page_indicator: ^1.2.0+3

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

  hive_generator: ^2.0.1
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
    - assets/vectors/
